ruby:
  version:
    2.3.0

dependencies:
  pre:
    - gem uninstall bundler # use a custom version of bundler

test:
  override:
    - bundle install: # note ':' here
        timeout: 180 # fail if command has no output for 3 minutes
