diff --git a/.codeclimate.yml b/.codeclimate.yml
index e69de29..e3e3bd5 100644
--- a/.codeclimate.yml
+++ b/.codeclimate.yml
@@ -0,0 +1,25 @@
+---
+engines:
+  duplication:
+    enabled: true
+    config:
+      languages:
+      - ruby
+  fixme:
+    enabled: true
+  rubocop:
+    enabled: true
+ratings:
+  paths:
+  - "**.rb"
+exclude_paths:
+- spec/
